{% set python_min = "3.10" %}
{% set name = "streamlit-searchbox" %}
{% set version = "0.1.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/streamlit_searchbox-{{ version }}.tar.gz
  sha256: b1682b75ce8839950287eb6e3509107ccbf8d4faad1b29bfdab64972621d59af

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - streamlit >=1.10.0

test:
  imports:
    - streamlit_searchbox
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/m-wrzr/streamlit-searchbox
  summary: Autocomplete Searchbox
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ytausch
